<a href="https://colab.research.google.com/github/ranesh88/Recommendation-System/blob/main/KNN_RS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [ ]:
movie = pd.read_csv("movies.csv")
rating = pd.read_csv("ratings.csv")

In [ ]:
movie.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [ ]:
rating.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [ ]:
movie_final = pd.merge(movie,rating,on="movieId")

In [ ]:
movie_final.drop(["genres","timestamp"],axis=1,inplace=True)

In [ ]:
movie_final.head()

movieId             title  userId  rating
0        1  Toy Story (1995)       7     3.0
1        1  Toy Story (1995)       9     4.0
2        1  Toy Story (1995)      13     5.0
3        1  Toy Story (1995)      15     2.0
4        1  Toy Story (1995)      19     3.0

In [ ]:
movie_final.shape

(100004, 4)

In [ ]:
movie_user_matrix = movie_final.pivot_table(index="title",columns="userId",values="rating")

In [ ]:
movie_user_matrix.head()

userId                                   1    2    3    4    5    6    7    \
title                                                                        
"Great Performances" Cats (1998)         NaN  NaN  NaN  NaN  NaN  NaN  NaN   
$9.99 (2008)                             NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Neath the Arizona Skies (1934)          NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Round Midnight (1986)                   NaN  NaN  NaN  NaN  NaN  NaN  NaN   

userId                                   8    9    10   ...  662  663  664  \
title                                                   ...                  
"Great Performances" Cats (1998)         NaN  NaN  NaN  ...  NaN  NaN  NaN   
$9.99 (2008)                             NaN  NaN  NaN  ...  NaN  NaN  NaN   
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  ...  NaN  NaN  NaN   
'Neath the Arizona Skies (1934)          NaN  NaN  NaN  ...  NaN  NaN  NaN   
'Round Midnight (1986)                   NaN  NaN  NaN  ...  NaN  NaN  NaN   

userId                                   665  666  667  668  669  670  671  
title                                                                       
"Great Performances" Cats (1998)         NaN  NaN  NaN  NaN  NaN  NaN  NaN  
$9.99 (2008)                             NaN  NaN  NaN  NaN  NaN  NaN  NaN  
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
'Neath the Arizona Skies (1934)          NaN  NaN  NaN  NaN  NaN  NaN  NaN  
'Round Midnight (1986)                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 671 columns]

In [ ]:
movie_user_matrix.fillna(0,inplace=True)

In [ ]:
movie_user_matrix.head()

userId                                   1    2    3    4    5    6    7    \
title                                                                        
"Great Performances" Cats (1998)         0.0  0.0  0.0  0.0  0.0  0.0  0.0   
$9.99 (2008)                             0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                   8    9    10   ...  662  663  664  \
title                                                   ...                  
"Great Performances" Cats (1998)         0.0  0.0  0.0  ...  0.0  0.0  0.0   
$9.99 (2008)                             0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId                                   665  666  667  668  669  670  671  
title                                                                       
"Great Performances" Cats (1998)         0.0  0.0  0.0  0.0  0.0  0.0  0.0  
$9.99 (2008)                             0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 671 columns]

In [ ]:
movie_user_matrix.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
movie_user_csr = csr_matrix(movie_user_matrix.values)

In [ ]:
knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute',n_neighbors=20)

In [ ]:
knn.fit(movie_user_csr)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=20)

In [ ]:
movie_user_matrix.iloc[100,:]

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
667    0.0
668    0.0
669    0.0
670    0.0
671    0.0
Name: 36th Chamber of Shaolin, The (Shao Lin san shi liu fang) (Master Killer) (1978), Length: 671, dtype: float64

In [ ]:
distances, indices = knn.kneighbors(movie_user_matrix.iloc[100,:].values.reshape(1,-1))

In [ ]:
distances

array([[0.        , 0.00221484, 0.01941932, 0.05187756, 0.08532319,
        0.10557281, 0.14481389, 0.18350342, 0.18350342, 0.22932536,
        0.23490794, 0.29289322, 0.29289322, 0.29289322, 0.29289322,
        0.29289322, 0.29289322, 0.29289322, 0.29289322, 0.29289322]])

In [ ]:
indices

array([[ 100, 1600, 4498, 5144, 4362, 5433, 5882, 2832, 2329,  492, 5944,
        2338, 2342, 2339, 2853, 2336, 2343, 7591, 6862, 2344]])

In [ ]:
for index in indices:
    print(movie_user_matrix.index[index])

Index(['36th Chamber of Shaolin, The (Shao Lin san shi liu fang) (Master Killer) (1978)',
       'Choke (2008)', 'Lady Snowblood (Shurayukihime) (1973)',
       'Meet the Feebles (1989)', 'Kickboxer (1989)', 'Munchies (1987)',
       'Ong-Bak 2: The Beginning (Ong Bak 2) (2008)',
       'Fist of Fury (Chinese Connection, The) (Jing wu men) (1972)',
       'Drag Me to Hell (2009)', 'Anvil! The Story of Anvil (2008)',
       'Outlander (2008)',
       'Dragon Ball Z: Cooler's Revenge (Doragon bôru Z 5: Tobikkiri no saikyô tai saikyô) (1991)',
       'Dragon Ball Z: The Return of Cooler (Doragon bôru Z 6: Gekitotsu! Hyakuoku pawâ no senshi) (1992)',
       'Dragon Ball Z: Dead Zone (Doragon bôru Z 1: Ora no Gohan wo kaese) (1989)',
       'Flesh Gordon (1974)',
       'Dragon Ball Z: Bio-Broly (Doragon bôru Z 11: Sûpâ senshi gekiha! Katsu no wa ore da) (1994)',
       'Dragon Ball Z: Wrath of the Dragon (Doragon bôru Z 13: Ryûken bakuhatsu!! Gokû ga yaraneba dare ga yaru) (1995)',
       